Fix testing pipelines
Biomapas/B.CfnS3LargeDeployment pull request #5
Opened 2021-09-16 19:17 UTC by gMatas

2021-09-17 11:49 UTC, gMatas commented on .github/workflows/pipeline-main.yml
> +          rm -rf b_cfn_s3_large_deployment_tests
Sia eilute pridejau, kad buildo metu nebutu supackaginami ir testu failai

2021-09-17 13:58 UTC, laimonassutkus requested changes

2021-09-17 13:58 UTC, laimonassutkus commented on .github/workflows/pipeline-main.yml
> +          rm -rf b_cfn_s3_large_deployment_tests
Kad nebutu packiganimi, reikia valdyti per setup.py, o ne per cia.

2021-09-17 13:58 UTC, laimonassutkus commented on .github/workflows/pipeline-default.yml
> +          python -c "\
Valdyti per infrastrucute.py arba app.py, o ne per cia.

2021-09-20 09:56 UTC, gMatas commented on .github/workflows/pipeline-main.yml
> +          rm -rf b_cfn_s3_large_deployment_tests
done

2021-09-20 09:56 UTC, gMatas commented on .github/workflows/pipeline-default.yml
> +          python -c "\
done

2021-09-20 10:11 UTC, laimonassutkus approved these changes

2021-09-20 10:11 UTC, merged